export {default as welcome} from './getData/welcome'
export {default as project} from './getData/project'
export {default as shopCar} from './getData/shopCar'
export {default as order} from './getData/order'
export {default as pc} from './getData/pc'
